apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
spec:
  selector:
    app: camunda
  type: LoadBalancer
  ports:
   - port: 80
     name: http
     targetPort: 8080
     protocol: TCP
